---
dist: focal
sudo: required

services:
  - docker

language: python
python: 3.9

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  - OS=alpine_3.12
  - OS=alpine_3.13
  - OS=alpine_edge
  - OS=archlinux_latest
  - OS=centos_8
  - OS=debian_bullseye
  - OS=debian_buster
  - OS=debian_stretch
  - OS=fedora_34
  - OS=fedora_35
  - OS=ubuntu_bionic
  - OS=ubuntu_focal
  - OS=ubuntu_xenial
    
script:
  - >-
    dcb
    --snippetsdir .
    --snippet from.j2 ansible-playbook.j2 onbuild-ansible-test.j2
    --upstreamgroup andrewrothstein
    --upstreamapp docker-ansible
    --pullall
    --writeall
    --buildall
    --pushall
    --alltags ${OS}
