---
dist: xenial
sudo: required

services:
  - docker

language: python
python: 3.7

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  - OS=alpine_3.10
  - OS=alpine_3.11
  - OS=alpine_3.12
  - OS=alpine_edge
  - OS=archlinux_latest
  - OS=centos_7
  - OS=centos_8
  - OS=debian_stretch
  - OS=debian_buster
  - OS=fedora_31
  - OS=fedora_32
  - OS=gentoo_latest
  - OS=ubi8_8.0
  - OS=ubi8_8.1
  - OS=ubi8_8.2
  - OS=ubuntu_bionic
  - OS=ubuntu_focal
  - OS=ubuntu_xenial
    
script:
  - >-
    dcb
    --snippetsdir .
    --snippet from.j2 ansible-playbook.j2 onbuild-ansible-test.j2
    --upstreamgroup andrewrothstein
    --upstreamapp docker-ansible
    --pullall
    --writeall
    --buildall
    --pushall
    --alltags ${OS}
